In [1]:
import numpy as np

In [17]:
#create an array with 10^7 elements
arr = np.arange(1e7)

In [13]:
#Converting ndarray to list
larr = arr.tolist()

In [20]:
#List Cannot by default broadcast, so a fucntion is coded to emulate
#what an ndarray can do
def list_times(alist,scalar):
    for i, val in enumerate(alist):
        alist[i]=val*scalar
    return alist


In [23]:
#Using Ipython's magic timeit command
timeit arr * 1.1

SyntaxError: invalid syntax (<ipython-input-23-e6c20bd0336f>, line 2)

In [22]:
timeit list_times(larr,1.1)

1 loops, best of 3: 1.03 s per loop


In [44]:
#creating a 3D numpy array
arr = np.zeros((3,3,3))

In [26]:
#Trying to convert array to a matrix, which will not work
mat = np.matrix(arr)

ValueError: shape too large to be a matrix.

# 2.Array Creation and Data Typing

In [29]:
#First we create a list and then wrap it with the np.array()function.
alist = [1,2,3]
arr = np.array(alist)

In [31]:
#Creating an array of zeros with five elements
arr= np.zeros(5)

In [33]:
#What if we want to create an array going from o to 100?
arr = np.arange(100)

In [35]:
#Or 10 to 100?
arr = np.arange(10,100)

In [37]:
#If you want 100 steps from 0 to 1...
arr = np.linspace(0,1,100)

In [39]:
#Or if you want to generate an array from 1 to 10 in log10 space in 100 steps
arr=np.logspace(0,1,100,base=10.0)

In [42]:
#Creating a 5x5 array of zeros(an image)
image = np.zeros((5,5))

In [50]:
#Creating a 5x5x5 cube of 1's 
#The astype() method sets the array with integer elements/
cube=np.zeros((5,5,5)).astype(int)+1

In [52]:
#Or even simpler with 16-bit floating-point precision...
cube = np.ones((5,5,5)).astype(np.float16)

In [54]:
#Array of zero integers
arr = np.zeros(2,dtype=int)

In [56]:
#Array of zero floats
arr = np.zeros(2,dtype=np.float32)

In [58]:
#Creating an array with elements from 0 to 999
arr1d = np.arange(1000)

In [60]:
#Now reshaping the array to a 10x10x10 3D array
arr3d = arr1d.reshape((10,10,10))

In [63]:
#The reshape command can alternatively be called this way 
arr3d = np.reshape(arr1d,(10,10,10))

In [65]:
#Inversely, we can flatten arrays
arr4d = np.zeros((10,10,10,10))

In [67]:
arr1d = arr4d.ravel()

In [73]:
print arr1d.shape

(10000,)


# Record Arrays

In [74]:
#Creating an array of zeros and defining column types
recarr = np.zeros((2,),dtype=('i4,f4,a10'))
toadd=[(1,2.,'Hello'),(2,3.,"World")]
recarr[:]=toadd

In [75]:
recarr

array([(1, 2.0, 'Hello'), (2, 3.0, 'World')], 
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', 'S10')])

In [76]:
#Creating an array of zeros and defining column types 
recarr = np.zeros((2,),dtype=('i4,f4,a10'))

In [78]:
#Now Creating the columns we want to put
col1 = np.arange(2)+1
col2 = np.arange(2,dtype=np.float32)
col3 = ['Hello','World']

In [82]:
#Here we create a list of tuples that is identical to the previous toadd list
toadd = zip(col1,col2,col3)

[(1, 0.0, 'Hello'), (2, 1.0, 'World')]

In [83]:
#Assigning values to recarr
recarr[:]=toadd

In [85]:
#Assigning names to each column,which are now by default called 'fo','f1', and 'f2'
recarr.dtype.names=('Integers','Floats','String')

In [87]:
#If we want to  access one of the columns by its name,we can do the following
recarr('Integers')

TypeError: 'numpy.ndarray' object is not callable

# Indexing and Slicing

In [88]:
alist = [[1,2],[3,4]]
#To return the (0,1) element we must index as shown below.
alist[0][1]

2

In [89]:
#Converting the list defined above into an array
arr = np.array(alist)

In [91]:
#To return the (0,1) element we use...
arr[0,1]

2

In [92]:
#Now to access the last column, we simply use..
arr[:1]

array([[1, 2]])

In [93]:
#Accessing the columns is achieved in the same way, which is the bottom row
arr[1,:]

array([3, 4])

In [94]:
#Creating an array
arr = np.arange(5)

In [100]:
#Creating the index array
index = np.where(arr>2)
index

(array([3, 4]),)

In [101]:
#Creating the desired array
new_arr = arr[index]

In [102]:
##Delete. We use the previous array
new_arr = np.delete(arr,index)

In [105]:
#Using boolean function to do that
index = arr>2
index

array([False, False, False,  True,  True], dtype=bool)

In [106]:
new_arr = arr[index]

# 2.2 Boolean Statements and Numpy Arrays

In [107]:
#Creating an image
img1 = np.zeros((20,20))+3
img1[4:-4,4:-4]=6
img1[7:-7,7:-7]=9
#See Plot A

In [110]:
#Let's filter out all values larger than 2 and less than 6
index1 = img1>2
index2 = img1<6
compound_index = index1&index2

In [112]:
#The compund statement can alternatively be written as 
compound_index = (img1>3)&(img1<7)
img2 = np.copy(img1)
img2[compound_index]=0
#See Plot B.

In [113]:
#Making the boolean arrays even more complex
index3 = img1 == 9
index4 = (index1&index2)|index3
img3 = np.copy(img1)
img3[index4]=0
#See Plot C.

In [116]:
###Only want to operate on specific elements in an array
import numpy as np
import numpy.random as rand
##Creating a 100-element array with random values
##from a standard normal distribution or , in other 
#words, a Gaussian distribution.
#The sigma is 1 and the mean is 0.
a = rand.randn(100)

In [118]:
#Here we generate an index for filtering o
#out undesired elements.
index = a>0.2
b = a[index]

In [120]:
#We execute some operation on the desited elements
b = b**2-2

In [122]:
#Then we put the modified elements back into the original array.
a[index]=b

# Text Files

In [125]:
#Opening the text file with the 'r' option,
#which only allows reading capability
f = open('somefile.txt','r')

In [126]:
#Parsing the file and splitting each line,
#which creates a list where each element of 
#it is one line
alist = f.readlines()

In [127]:
##Closing file
f.close()

In [128]:
##we open a new text file to write the data with the 'w' option
#if there was data already existing in the file, it will be overwrriten.
f = open('newtextfile.txt','w')

In [129]:
#Writing data to file 
f.writelines(newdata)

NameError: name 'newdata' is not defined

In [130]:
#Closing file
f.close()

In [131]:
##Getting the data direclty into a numpy.ndarray
import numpy as np
arr = np.loadtxt('somefile.txt')
np.savetxt('somenewfile.txt')

/Users/AlexCen1/anaconda/lib/python2.7/site-packages/numpy/lib/npyio.py:776: UserWarning: loadtxt: Empty input file: "somefile.txt"
  warnings.warn('loadtxt: Empty input file: "%s"' % fname)


TypeError: savetxt() takes at least 2 arguments (1 given)

In [141]:
#example.txt file looks like the following 
#XR 21 32.789 1
#XR 22 33.091 2
table = np.loadtxt('somefile.txt',dtype= ('ID','Result','Type'),
                  'formats': ('S4','f4','i2'))
table

SyntaxError: invalid syntax (<ipython-input-141-d55d8e2fdc4b>, line 5)

# 2.3 Binary Files

In [1]:
import numpy as np

In [2]:
#Creating a large array
data = np.empty((1000,1000))

In [4]:
np.save('test.npy',data)

In [5]:
#If space is an issue for large files, then 
#use numpy.savez instead. It is slower than 
#numpy.save because it compresses the binary file.
np.savez('test.npz',data)

In [7]:
#Loading the data array
newdata = np.load('test.npy')

In [8]:
newdata

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

# 2.4 Math

In [9]:
##2.4.1 Linear Algebra
import numpy as np

In [11]:
#Defining the matrices
A = np.matrix([[3,6,-5],[1,-3,2],[5,-1,4]])
B = np.matrix([[12],[-2],[10]])

In [12]:
#Solving for the variables, where we invert A
X = A ** (-1)*B
X

matrix([[ 1.75],
        [ 1.75],
        [ 0.75]])

In [16]:
#Alternatively
a = np.array([[3,6,-5],[1,-3,2],[5,-1,4]])

In [17]:
#Defining the array
b = np.array([12,-2,10])

In [18]:
#Solving for the variables, where we invert A
x = np.linalg.inv(a).dot(b)
x

array([ 1.75,  1.75,  0.75])

In [22]:
np.linalg.inv(a)

array([[ 0.15625 ,  0.296875,  0.046875],
       [-0.09375 , -0.578125,  0.171875],
       [-0.21875 , -0.515625,  0.234375]])