# 3.1.1 Data Modeling and Fitting

# 3.1 Curve_fit. Find the best parameters

In [1]:
import numpy as np
from scipy.optimize import curve_fit

In [2]:
#Creating a function to model and create data
def func(x,a,b):
    return a*x+b

In [3]:
#Generating clean data
x = np.linspace(0,10,100)
y = func(x,1,2)

In [4]:
#Adding noise to the data
yn = y+0.9*np.random.normal(size=len(x))

In [6]:
#Executing curve_fit on noisy data
popt,pcov = curve_fit(func,x,yn)

In [7]:
#popt returns the best fir values for parameters of the 
#given model(func).

In [8]:
popt

array([ 0.99722223,  2.13209517])

In [ ]:
###check the quality of the fit with pcov

In [9]:
#Creating a function to model and create data
def func(x,a,b,c):
    return a*np.exp(-(x-b)**2/(2*c**2))

In [10]:
#Generating clean data
x = np.linspace(0,10,100)
y = func(x,1,5,2)

In [11]:
#Adding noise to the data 
yn = y+0.2*np.random.normal(size=len(x))

In [12]:
#Executing curve_fit on noisy data
popt,pcov = curve_fit(func,x,yn)

In [13]:
#popt returns the best-fit values for parameters of the given model(func)
popt

array([ 1.02570894,  4.99078855, -1.92682167])

In [15]:
###Two-Gaussian model
def func(x,a0,b0,c0,a1,b1,c1):
    return a0*np.exp(-(x-b0)**2/(2*c0**2))\
        +a1*np.exp(-(x-b1)**2/(2*c1**2))

In [16]:
#Generating clean data
x = np.linspace(0,20,200)
y = func(x,1,3,1,-2,15,0.5)

In [17]:
#Adding noise to the data 
yn = y+0.2*np.random.normal(size=len(x))

In [18]:
#Since we are fitting a more complex function, 
#providing guesses for the fitting will lead to 
#better results
guesses=[1,3,1,1,15,1]
#Executing curve_fit on noisy data
popt,prov = curve_fit(func,x,yn,p0=guesses)

In [19]:
popt

array([  1.01427407,   2.88595811,   1.00665975,  -1.95092546,
        15.03782582,   0.50428664])

In [20]:
##Solutions to Functions
#scipy.optimize.fsolve

In [22]:
from scipy.optimize import fsolve
import numpy as np

In [30]:
line = lambda x:x+2

In [35]:
solution = fsolve(line,-2)
solution

array([-2.])

In [36]:
#Finding the intersection points between two equations is nearly as simple
from scipy.optimize import fsolve
import numpy as np

In [40]:
#Defining function to simplify intersection solution
def findIntersection(func1,func2,x0):
    return fsolve(lambda x:func1(x)-func2(x),x0)

In [41]:
#Defining functions that will intersect
funky = lambda x:np.cos(x/5)*np.sin(x/2)
line = lambda x:0.01*x-0.5

In [46]:
#Defining range and getting solutions on intersection points
x = np.linspace(0,45,10000)
result = findIntersection(funky,line,[15,20,30,35,40,45])

In [47]:
#Printing out results for x and y
print(result,line(result))

(array([ 13.40773078,  18.11366128,  31.78330863,  37.0799992 ,
        39.84837786,  43.8258775 ]), array([-0.36592269, -0.31886339, -0.18216691, -0.12920001, -0.10151622,
       -0.06174122]))


# 3.2 Interpolation

In [1]:
import numpy as np
from scipy.interpolate import interp1d

In [14]:
#Setting up fake data
x = np.linspace(0,10*np.pi,20)
y = np.cos(x)

In [15]:
#Interpolating data
f1 = interp1d(x,y,kind='linear')
fq = interp1d(x,y,kind='quadratic')

In [5]:
#x.min and x.max are used to make sure we do not
#go beyond the boundaries of the data for the interpolation
xint = np.linspace(x.min(),x.max(),1000)
yint1 = f1(xint)
yintq = fq(xint)

In [10]:
###3.2.2 Interpolate noisy data with univariate example

In [9]:
import numpy as np
import matplotlib.pyplot as mpl
from scipy.interpolate import UnivariateSpline

In [11]:
#Setting up fake data with artificial noise
sample = 30
x = np.linspace(1,10*np.pi,sample)
y = np.cos(x)+np.log10(x)+np.random.randn(sample)/10

In [12]:
#Interpolating the data
f = UnivariateSpline(x,y,s=1) 
#the option s is the smppthing factor, which should be used when fitting data with noise
#if instead s =0, then the interpolation will go through all points while ignoring all noise

In [13]:
#x.min and x.max are used to make sure we do not 
#go beyond the boundaries of the data for the interpolation.
xint = np.linspace(x.min(),x.max(),1000)
yint = f(xint)

In [17]:
###3.2.3 Interpolate noisy data with multivariate example
import numpy as np
from scipy.interpolate import griddata

In [18]:
#Defining a function 
ripple = lambda x,y:np.sqrt(x**2+y**2)+np.sin(x**2+y**2)

In [19]:
#Generating gridded data. The complex number defines
#how many steps the grid data should have. Without the 
#complex number mgrid would only create a grid data structure
#with 5 steps.
grid_x,grid_y = np.mgrid[0:5:1000j,0:5:1000j]

In [20]:
#Generating sample that interpolation function will see
xy = np.random.rand(1000,2)
sample = ripple(xy[:,0]*5,xy[:,1]*5)

In [21]:
#Interpolating data with a cubic
grid_z0 = griddata(xy*5,sample,(grid_x,grid_y),method='cubic')

In [23]:
##
import numpy as np
from scipy.interpolate import SmoothBivariateSpline as SBS

In [24]:
#Definig a function
ripple = lambda x,y:np.sqrt(x**2+y**2)+np.sin(x**2+y**2)
x,y = xy[:,0],xy[:,1]
sample = ripple(xy[:,0]*5,xy[:,1]*5)

In [25]:
#Interpolating data 
fit = SBS(x*5,y*5,sample,s=0.01,kx=4,ky=4)
interp = fit(np.linspace(0,5,1000),np.linspace(0,5,1000))

/Users/AlexCen1/anaconda/lib/python2.7/site-packages/scipy/interpolate/fitpack2.py:931: UserWarning: ier=45589
  warnings.warn(message)


# 3.3 Integration

In [27]:
#3.3.1 Analytic Integration

In [28]:
import numpy as np
from scipy.integrate import quad

In [29]:
#Defining function to integrate
func = lambda x:np.cos(np.exp(x))**2

In [30]:
#Integrating function with upper and lower
#limits of 0 and 3, respectively 
solution = quad(func,0,3)
solution

(1.296467785724373, 1.397797186265988e-09)

In [31]:
#The first element is the desired value
#and the second is the error

In [32]:
##3.3.2 Numerical Integration

In [33]:
import numpy as np
from scipy.integrate import quad,trapz

In [34]:
#Setting up fake data
x = np.sort(np.random.randn(150)*4+4).clip(0,5)
func = lambda x: np.sin(x)*np.cos(x**2)+1
y = func(x)

In [35]:
#Integrating function with upper and lower
#Limits of 0 and 5, respectively
fsolution = quad(func,0,5)
dsolution = trapz(y,x=x)

In [36]:
print('fsolution = '+str(fsolution[0]))
print('dsolution = '+str(dsolution))
print('The difference is'+str(np.abs(fsolution[0]-dsolution)))

fsolution = 5.10034506754
dsolution = 5.19752966411
The difference is0.0971845965696


# 3.4 Statistics

In [39]:
import numpy as np

In [40]:
#Constructing a random array with 1000 elements
x = np.random.randn(1000)

In [41]:
#Calculating several of the built-in methods
#that numpy.array has
mean = x.mean()
std = x.std()
var = x.var()

# 3.4.1 Continuous and Discrete distributions

In [43]:
import numpy as np 
from scipy.stats import norm

In [44]:
#Set up the sample range
x = np.linspace(-5,5,1000)

In [45]:
#Here set up the parameters for the normal distribution,
#where loc is the mean and scale is the standard deviation.
dist = norm(loc=0,scale=1)

In [47]:
#Retrieving norm's PDF and CDF
pdf = dist.pdf(x)
cdf = dist.cdf(x)

In [49]:
#Here we draw out 500 random values from the norm.
sample = dist.rvs(500)

In [51]:
#
import numpy as np
from scipy.stats import geom

In [52]:
#Here set up the parameters fro the meometric distribution
p = 0.5
dist = geom(p)

In [53]:
#Set up the sample range
x = np.linspace(0,5,1000)

In [54]:
#Retrieving geom's PMF and CDF 
pmf = dist.pmf(x)
cdf = dist.cdf(x)

In [55]:
#Here we draw out 500 random values
sample = dist.rvs(500)

# 3.4.2 Functions

In [56]:
import numpy as np
from scipy import stats

In [57]:
#Generating a normal distribution sample
#with 100 elements
sample = np.random.randn(100)

In [58]:
#Normaltest tests the null hypothesis.
out = stats.normaltest(sample)
print('normaltest output')
print('Z-score='+str(out[0]))
print('P-value='+str(out[1]))

normaltest output
Z-score=0.372630023713
P-value=0.830012090146


In [62]:
#kstest is the Kolmogorov-Smirnov test for goodness of fit.
#Here its sample is being tested against the normal distribution.
#D is the KS statistic and the closer it is to 0 the better.
out = stats.kstest(sample,'norm')
print('\nkstest output for the Normal distribution')
print('D= '+str(out[0]))
print('P-value='+str(out[1]))


kstest output for the Normal distribution
D= 0.108403416128
P-value=0.177198754279


In [63]:
#Similarly, this can be easily tested against other distributions,
#like the Wald distribution.
out = stats.kstest(sample,'wald')
print('\nkstest output for the Wald distribution')
print('D='+str(out[0]))
print('P-value='+str(out[1]))


kstest output for the Wald distribution
D=0.469992263215
P-value=0.0


In [64]:
import numpy as np
from scipy import stats

In [65]:
#Generating a normal distribution sample
#with 100 elements
sample = np.random.randn(100)

In [66]:
#The harmonic mean:Sample values have to 
#be greater than 0.
out = stats.hmean(sample[sample>0])
print('Harmonic mean='+str(out))

Harmonic mean=0.249416392778


In [67]:
#The mean,where values below -1 and above 1 are
#removed for the mean calculation
out = stats.tmean(sample,limits=(-1,1))
print('\nTrimmed mean='+str(out))


Trimmed mean=-0.00497096341963


In [68]:
#Calculating the skewness of the sample
out = stats.skew(sample)
print('\nSkewness='+str(out))


Skewness=-0.209745338686


In [69]:
#Additionally, there is a handy summary function called
#describe, which gives a quick look at the data.
out = stats.describe(sample)
print('\nSize='+str(out[0]))
print('Min='+str(out[1][0]))
print('Max='+str(out[1][1]))
print('Mean='+str(out[2]))
print('Variance='+str(out[3]))
print('Skewness='+str(out[4]))
print('Kurtosis='+str(out[5]))


Size=100
Min=-2.56237406016
Max=2.04908323788
Mean=-0.0496547319821
Variance=1.08223066532
Skewness=-0.209745338686
Kurtosis=-0.409599342968


# 3.5 Spatial and Clustering Analysis

In [71]:
#3.5.1 Vector Quantization
import numpy as np
from scipy.cluster import vq

In [72]:
#Creating data
c1 = np.random.randn(100,2)+5
c2 = np.random.randn(30,2)-5
c3 = np.random.randn(50,2)

In [73]:
#Pooling all the data into one 180x2 array
data = np.vstack([c1,c2,c3])

In [74]:
#Calculating the cluster centroids and variance
#from kmeans
centroids,variance = vq.kmeans(data,3)

In [75]:
#The identified variable contains the information
#we need to separate the points in clusters
#based on the vq function.
identified,distance = vq.vq(data,centroids)

In [76]:
#Retrieving coordinates for points in each vq
#identified core
vqc1 = data[identified ==0] #the first cluster
vqc2 = data[identified ==1] #the second cluster
vqc3 = data[identified ==2] #the third cluster

# 3.5.2 Hierarchical Clustering 

In [5]:
import numpy as np
import matplotlib.pyplot as mpl
from mpl_toolkits.mplot3d import Axes3D
from scipy.spatial.distance import pdist,squareform
import scipy.cluster.hierarchy as hy

In [6]:
#Creating a cluster of clusters function
def clusters(number=20,cnumber=5,csize=10):
    #Note that the way the clusters are postioned is Gaussian randomness.
    rnum = np.random.rand(cnumber,2)
    rn = rnum[:,0]*number
    rn = rn.astype(int)
    rn[np.where(rn<5)]=5
    rn[np.where(rn>number/2.)] = round(number/2.,0)
    ra = rnum[:,1]*2.9
    ra[np.where(ra<1.5)]=1.5
    cls = np.random.randn(number,3)*csize
    #Random multipliers for central point of cluster
    rxyz = np.random.randn(cnumber-1,3)
    for i in xrange(cnumber-1):
        tmp = np.random.randn(rn[i+1],3)
        x = tmp[:,0]+(rxyz[i,0]*csize)
        y = tmp[:,1]+(rxyz[i,1]*csize)
        z = tmp[:,2]+(rxyz[i,2]*csize)
        tmp = np.column_stack([x,y,z])
        cls = np.vstack([cls,tmp])
    return cls

In [7]:
#Generate a cluster of clusters and distance matrix.
cls = clusters()
D = pdist(cls[:,0:2])
D = squareform(D)

In [8]:
#Compute and plot first dendrogram.
fig = mpl.figure(figsize=(8,8))
ax1 = fig.add_axes([0.09,0.1,0.2,0.6])
Y1 = hy.linkage(D,method='complete')
cutoff = 0.3*np.max(Y1[:,2])
Z1 = hy.dendrogram(Y1,orientation='right',color_threshold=cutoff)
ax1.xaxis.set_visible(False)
ax1.yaxis.set_visible(False)

In [9]:
#Compute and plot second dendrogram.
ax2 = fig.add_axes([0.3,0.71,0.6,0.2])
Y2 = hy.linkage(D,method='average')
cutoff = 0.3*np.max(Y2[:,2])
Z2 = hy.dendrogram(Y2,color_threshold=cutoff)
ax2.xaxis.set_visible(False)
ax2.yaxis.set_visible(False)

In [10]:
#Plot distance matrix.
ax3 = fig.add_axes([0.3,0.1,0.6,0.6])
idx1 = Z1['leaves']
idx2 = Z2['leaves']
D = D[idx1,:]
D = D[:,idx2]
ax3.matshow(D,aspect='auto',origin='lower',cmap=mpl.cm.YlGnBu)
ax3.xaxis.set_visible(False)
ax3.yaxis.set_visible(False)

In [11]:
#Plot colorbar
fig.savefig('cluster_hy_f01.pdf',bbox='tight')

In [12]:
#Distinguish the structures from one another

In [13]:
#Same imports and cluster function from the previous example
#follow through here.
#Here we define a function to collect the coordinates of 
#each point of the different clusters

In [14]:
def group(data,index):
    number = np.unique(index)
    groups = []
    for i in number:
        groups.append(data[index==i])
    return groups

In [15]:
#Creating a cluster of clusters 
cls = clusters()

In [16]:
#Calculating the linkage matrix
Y = hy.linkage(cls[:,0:2],method='complete')

In [18]:
#Here we use the fcluster function to pull out a 
#collection of flat clusters from the hierarchical
#data structure.Note that we are using the same cutoff value as 
#in the previous example for the dendrogram
#using the 'complet' method.
cutoff = 0.3*np.max(Y[:,2])
index = hy.fcluster(Y,cutoff,'distance')


In [21]:
#Using the group function, we group points into their
#respective clusters
groups = group(cls,index)

In [25]:
#Plotting clusters
fig = mpl.figure(figsize=(6,6))
ax = fig.add_subplot(111)
colors = ['r','c','b','g','orange','k','y','gray']
for i,g in enumerate(groups):
    i = np.mod(i,len(colors))
    ax.scatter(g[:,0],g[:,1],c=colors[i],edgecolor='none',s=50)
    ax.xaxis.set_visible(False)
    ax.yaxis.set_visible(False)

In [26]:
fig.savefig('cluster_hy_f02.pdf',bbox='tight')


# 3.6 Signal and Image Processing

In [27]:
import numpy as np
from scipy.misc import imread,imsave
from glob import glob

In [28]:
#Getting the list of files in the directory 
files = glob('space/*.JPG')

In [31]:
#Opening up the first image for loop
for i in xrange(1,len(files)):
    print i 
    im1 += imread(files[i]).astype(np.float32)

In [32]:
#Saving img
imsave('stacked_image.jpg',im1)

NameError: name 'im1' is not defined

In [33]:
import numpy as np
from scipy.misc import imread,imsave
from glob import glob

In [34]:
#This function allows us to place in the 
#brightest pixels per x and y position between 
#two images. It is similar to PIL's 
#ImageChop.Lighter function.
def chop_lighter(image1,image2):
    s1 = np.sum(image1,axis=2)
    s2 = np.sum(image2,axis=2)
    index = s1<s2
    image1[index,0]=image2[index,0]
    image1[index,1]=image2[index,1]
    image1[index,2]=image2[index,2]
    return image1


In [35]:
#Getting the list of files in the direactory 
files = glob('space/*.JPG')

In [36]:
#Opening up the first image for looping 
im1 = imread(files[0]).astype(np.float32)
im2 = np.copy(im1)

IndexError: list index out of range

In [37]:
#Starting loop
for i in xrange(1,len(files)):
    print i 
    im = imread(files[i]).astype(np.float32)
    #same before 
    im1 += im
    #im2 shows star trails better
    im2 = chop_lighter(im2,im)

In [38]:
#Saving image with slight tweaking on the combination 
#of the two images to show star trails with the co-added images.
imsave('stack_image.jpg',im1/im1.max()+im2/im2.max()*0.2)

NameError: name 'im1' is not defined

# 3.7 Sparse Matrices

In [39]:
import numpy as np
from scipy.sparse.linalg import eigsh
from scipy.linalg import eigh
import scipy.sparse
import time

In [40]:
N = 3000
#Creating a random sparse matrix 
m = scipy.sparse.rand(N,N)

In [41]:
#Creating an array clone of it
a = m.toarray()

In [42]:
print('The numpy array data size:'+str(a.nbytes)+'bytes')
print('The sparse matrix data size:'+str(m.data.nbytes)+'bytes')

The numpy array data size:72000000bytes
The sparse matrix data size:720000bytes


In [43]:
#Non-sparse
to = time.time()

In [46]:
res1 = eigh(a)
dt = str(np.round(time.time()-to,3))+'seconds'
print('Non-sparse operation takes'+dt)

Non-sparse operation takes72.48seconds


In [47]:
#Sparse
to = time.time()
res2 = eigsh(m)
dt = str(np.round(time.time()-to,3))+'seconds'
print('Sparse operation takes'+dt)

Sparse operation takes0.055seconds
